#!/bin/bash

kernelName="$(uname -s)"

# pwd
# ls -al

# Function that computes absolute path of a file
abs_path() {
  dir=$(dirname "$1")
  cd "$dir" >/dev/null 2>&1
  printf "%s/%s" "$(pwd)" "${1##*/}"
}

# Navigate to the directory where the current script resides
bashfile=$(abs_path "$0")
selfdir=$(dirname "$bashfile")
cd "$selfdir"

curl https://raw.githubusercontent.com/zackees/install.py/main/install.py -o install.py

if [ "$kernelName" == "Darwin" ]; then
    # Check if Homebrew is installed
    if command -v brew >/dev/null 2>&1; then
        echo "Homebrew is installed. Continuing with installation."
        brew install python@3.11
        python3.11 -m venv venv
        source venv/bin/activate
        python ./install.py
    else
        echo "Error: Homebrew is not installed. Please install Homebrew and rerun this script."
        exit 1
    fi
elif [ "$kernelName" == "Linux" ]; then
    sudo apt-get install python3.11 python3.11-venv
    python3.11 -m venv venv
    source venv/bin/activate
    python ./install.py
elif [[ "$kernelName" == CYGWIN* ]] || [[ "$kernelName" == MINGW32* ]] || [[ "$kernelName" == MSYS* ]] || [[ "$kernelName" == MINGW* ]]; then
   echo "Windows OS detected"
   python -m venv venv
   source venv/Scripts/activate
   python install.py
else
    # Error
    echo "Unknown operating system: $kernelName"
    exit 1
fi
