#!/bin/bash

set -e

# Set the --break-system-packages flag for Darwin (macOS) only
BREAK_FLAG=""
if [[ "$OSTYPE" == "darwin"* ]]; then
  BREAK_FLAG="--break-system-packages"
fi

# Determine the correct pip command based on the OS
if [[ "$OSTYPE" == "msys" ]]; then
  pip install uv $BREAK_FLAG
else
  pip3 install uv $BREAK_FLAG
fi

uv venv --python 3.11

# Install requirements from requirements.testing.txt if it exists
if [[ -f requirements.testing.txt ]]; then
  uv run pip install -r requirements.testing.txt
fi

uv run pip install -e .

# Remove the previous activation script if it exists
rm -rf ./activate

# Create symlink for the activation script
if [[ "$OSTYPE" == "msys" ]]; then
  ln -s .venv/Scripts/activate ./activate
  if [[ -d .git ]]; then
    git add ./activate --chmod=+x
  fi
else
  ln -s .venv/bin/activate ./activate
fi
